const D_DAY_START_DATE = 1;
const D_DAY_END_DATE = 25;
const WEEKDAY_START_DATE = 0;
const WEEKDAY_END_DATE = 4;
const WEEKEND_START_DATE = 5;
const WEEKEND_END_DATE = 6;
const SPECIAL_DATES = new Set([3, 10, 17, 24, 25, 31]);
const DEC_2023_STR = '2023-12-';

export {
	D_DAY_START_DATE,
	D_DAY_END_DATE,
	WEEKDAY_START_DATE,
	WEEKDAY_END_DATE,
	WEEKEND_START_DATE,
	WEEKEND_END_DATE,
	SPECIAL_DATES,
	DEC_2023_STR,
};
