const D_DAY_START_MONEY = 1_000;
const D_DAY_DISCOUNT_MONEY = 100;
const DESSERT_DISCOUNT_MONEY = 2_023;
const MAIN_DISCOUNT_MONEY = 2_023;
const SPECIAL_DISCOUNT_MONEY = 1_000;
const DISCOUNT_APPLY_LIMIT = 10_000;

export {
	D_DAY_START_MONEY,
	D_DAY_DISCOUNT_MONEY,
	DESSERT_DISCOUNT_MONEY,
	MAIN_DISCOUNT_MONEY,
	SPECIAL_DISCOUNT_MONEY,
	DISCOUNT_APPLY_LIMIT,
};
